name       : bovo
version    : 18.08.2
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/bovo-18.08.2.tar.xz : cb6fe9e5e5a47903fef7c730291a068fc5460609e2fca24fcf6d402e6c0245e6
license    : GPL-2.0
component  : games.strategy
summary    : A Gomoku like game for two players
description: |
    Bovo is a Gomoku like game for two players, where the opponents alternate in placing their respective pictogram on the game board. Also known as Connect Five, Five in a row, X and O, Naughts and Crosses.
builddeps  :
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kxmlgui-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
