name       : bovo
version    : 17.12.3
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/bovo-17.12.3.tar.xz : 498fcca291345cd5bba61f1163916ad059b7691083d10a3e910eff130072ea97
license    : GPL-2.0
component  : games.strategy
optimize   : lto
summary    : A Gomoku like game for two players
description: |
    Bovo is a Gomoku like game for two players, where the opponents alternate in placing their respective pictogram on the game board. Also known as Connect Five, Five in a row, X and O, Naughts and Crosses.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kxmlgui-devel
    - libkdegames-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
