name       : bovo
version    : 17.04.0
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.04.0/src/bovo-17.04.0.tar.xz : 623620b1aac8f67dafe2e02b9e7cf2df63dc48021b5604bc533cc81fc071b648
license    : GPL-2.0
component  : games.strategy
summary    : Bovo is a Gomoku like game for two players, where the opponents alternate in placing their respective pictogram on the game board. Also known as Connect Five, Five in a row, X and O, Naughts
    and Crosses.
description: |
    Bovo is a Gomoku like game for two players, where the opponents alternate in placing their respective pictogram on the game board. Also known as Connect Five, Five in a row, X and O, Naughts and Crosses.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kxmlgui-devel
    - libkdegames-devel
    - qt5-quickcontrols2-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
