name       : bovo
version    : 17.12.1
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/bovo-17.12.1.tar.xz : 0a4dc4ecd0d9a5fd573b33bfd1dec6e0ddd3b34f16da9dcbd31b4ec1c7654039
license    : GPL-2.0
component  : games.strategy
optimize   : lto
summary    : A Gomoku like game for two players
description: |
    Bovo is a Gomoku like game for two players, where the opponents alternate in placing their respective pictogram on the game board. Also known as Connect Five, Five in a row, X and O, Naughts and Crosses.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kxmlgui-devel
    - libkdegames-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
